### ISSUE TITLE
French Forvo is incompation with the Anki version above 23.10.

### ISSUE THREAD

**Issue by BilderLoong** [seth-js/yomichan-fr#3]
Here is the error message during Anki statup.

```
When loading French Forvo:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/birudo/Library/Application Support/Anki2/addons21/French Forvo/__init__.py", line 149, in <module>
    class ForvoHandler(http.server.SimpleHTTPRequestHandler):
  File "/Users/birudo/Library/Application Support/Anki2/addons21/French Forvo/__init__.py", line 150, in ForvoHandler
    forvo = Forvo("fr")
  File "/Users/birudo/Library/Application Support/Anki2/addons21/French Forvo/__init__.py", line 28, in __init__
    self._set_session()
  File "/Users/birudo/Library/Application Support/Anki2/addons21/French Forvo/__init__.py", line 35, in _set_session
    retry_strategy = Retry(
  TypeError: __init__() got an unexpected keyword argument 'method_whitelist'
  ```

**Comment by BilderLoong** [comment]
Here is the patch to fix this issue. I tried this on Anki version 23.10.1 and it worked well.
Since the French Forvo plugin isn't in this repo, I can't open PR.
Would you like to manually apply this patch to fix this issue or include the French Forvo plugin in this repo?

```diff
diff --git a/__init__.py b/__init__.py
index 9911932..c6c4d5f 100644
--- a/__init__.py
+++ b/__init__.py
@@ -36,7 +36,7 @@ class Forvo:
             total=3,
             backoff_factor=1,
             status_forcelist=[429, 500, 502, 503, 504],
-            method_whitelist=["HEAD", "GET", "OPTIONS"],
+            allowed_methods=["HEAD", "GET", "OPTIONS"],
         )
         adapter = HTTPAdapter(max_retries=retry_strategy)
         self.session = requests.Session()
```

And thank you for making this Yomichan work with French which helps me a lot during my learning journey.

**Comment by BilderLoong** [comment]
This is the file that has already applied this modification.
[French Forvo.zip](https://github.com/seth-js/yomichan-fr/files/13471992/French.Forvo.zip)

**Comment by seth-js** [comment]
Thanks for letting me know. The addon has been updated on the Releases page.

>And thank you for making this Yomichan work with French which helps me a lot during my learning journey.

No problem. I hope your studies go well.
